- name: Check if yay is installed
  ansible.builtin.stat:
    path: /usr/bin/yay
  register: yay_check

- name: Install yay if missing
  become: true
  pacman:
    name: yay
    state: present
  when: not yay_check.stat.exists

