
- name: Setup my eos system
  hosts: all
  roles:
    - role: base
      tags: [base]

    - role: zsh
      tags: [zsh]

    - role: ghostty
      tags: [ghostty]

    - role: hyprland
      tags: [hyprland]

    - role: dotfiles
      tags: [dotfiles]
